export const INFORMATION_TYPE_TEXT = 'text'
export const INFORMATION_TYPE_HTML = 'html'
export const INFORMATION_TYPE_DATES = 'dates'
export const INFORMATION_TYPE_DIVIDER = 'divider'
export const INFORMATION_TYPES = [INFORMATION_TYPE_TEXT, INFORMATION_TYPE_HTML, INFORMATION_TYPE_DATES, INFORMATION_TYPE_DIVIDER] as const