export const INFORMATION_TYPE_TEXT = 'text'
export const INFORMATION_TYPE_HTML = 'html'
export const INFORMATION_TYPE_DATES = 'dates'
export const INFORMATION_TYPE_DIVIDER = 'divider'
export const INFORMATION_TYPES = [INFORMATION_TYPE_TEXT, INFORMATION_TYPE_HTML, INFORMATION_TYPE_DATES, INFORMATION_TYPE_DIVIDER] as const

export const SORTER_TYPE_LETTERS = 'letters'
export const SORTER_TYPE_NUMBERS = 'numbers'
export const SORTER_TYPES = [SORTER_TYPE_LETTERS, SORTER_TYPE_NUMBERS] as const