query GetCoins($limit: Int!, $page: Int!, $sort: [String!]!, $filter: coins_filter!) {
	coins_aggregated {
    count {
      id
		}
	},
	total: coins(limit: -1, filter: $filter) {
		id
	}
	coins(limit: $limit, page: $page, filter: $filter, sort: $sort) {
		id
		identifier
		entity
		authority
		portrait
		date_from
		date_to
		image_obverse {
			id
		}
		image_reverse {
			id
		}
		mint
		material
		denomination
		comment
		reference
		bibliography
	}
}

query GetCoin($id: ID!) {
	coin: coins_by_id(id: $id) {
		id
		identifier
		entity
		authority
		portrait
		date_from
		date_to
		image_obverse {
			id
		}
		description_obverse
		image_reverse {
			id
		}
		description_reverse
		mint
		material
		denomination
		weight
		diameter
		axis
		comment
		date_explanation
		reference
		bibliography
	}
}
