query GetCoins($page: Int!) {
	coins(limit: 100, page: $page, filter: {status: {_eq: "pending"} }) {
		id
		identifier
		authority
		date_from
		date_to
		image_obverse {
			id
		}
		image_reverse {
			id
		}
		mint
		material
		denomination
	}
}

query GetCoin($id: ID!) {
	coin: coins_by_id(id: $id) {
		id
		identifier
		authority
		portrait
		date_from
		date_to
		image_obverse {
			id
		}
		obverse
		image_reverse {
			id
		}
		reverse
		mint
		material
		denomination
		weight
		diameter
		axis
		comment
		bibliography
	}
}
